### ISSUE TITLE
Fatal errors

### ISSUE THREAD

**Issue by khaneliman** [snowfallorg/frost#1]
Hey, came across this while trying to update my README and saw your documentation site mentioning this project. But, trying to run it I just get 

```
frost build github:khaneliman/khanelinix
   INFO   Frost Build
 ﮊ  FATAL  Frost Cannot read properties of undefined (reading 'kind')
 ﮊ  FATAL  Frost     at w.parseComments (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:9988)
 ﮊ  FATAL  Frost     at w.parseSubExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:6517)
 ﮊ  FATAL  Frost     at w.parseExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:3076)
 ﮊ  FATAL  Frost     at w.parseKeyword (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:13911)
 ﮊ  FATAL  Frost     at w.parseSubExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:5732)
 ﮊ  FATAL  Frost     at w.parseExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:3076)
 ﮊ  FATAL  Frost     at w.parseTokens (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:2985)
 ﮊ  FATAL  Frost     at w.parseInterp (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:7463)
 ﮊ  FATAL  Frost     at w.parseSubExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:5273)
 ﮊ  FATAL  Frost     at w.parseExpr (/nix/store/9pc8z2h0zgh8vfclm5jz9lxpj3rx5qm3-frost/lib/node_modules/frost/node_modules/@snowfallorg/sleet/dist/sleet.cjs.js:10:3076)

```

**Comment by jakehamilton** [comment]
Hey @khaneliman 👋 

Do you have a particular commit that this is throwing on? This error is caused by the parser (Sleet) failing to parse a Nix file.

**Comment by khaneliman** [comment]
Haven't tried bisecting it, just been using it as a flake overlay off main.

**Comment by jakehamilton** [comment]
Oh I meant a particular commit on your repo that this error appears when trying to run the tool.

**Comment by jakehamilton** [comment]
I'll try to take a look, this is definitely an issue with Sleet not parsing correctly.
